"""initial

Revision ID: d94fa56dc777
Revises: 
Create Date: 2025-11-02 19:53:42.160713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94fa56dc777'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_category_user_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('Index_category_global_name', ['name'], unique=True, postgresql_where=sa.text('owner_id IS NULL'))
        batch_op.create_index(batch_op.f('ix_categories_owner_id'), ['owner_id'], unique=False)

    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_record_amount_nonnegative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_records_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_datetime'), ['datetime'], unique=False)
        batch_op.create_index('ix_records_user_cat_dt', ['user_id', 'category_id', 'datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_user_id'))
        batch_op.drop_index('ix_records_user_cat_dt')
        batch_op.drop_index(batch_op.f('ix_records_datetime'))
        batch_op.drop_index(batch_op.f('ix_records_category_id'))

    op.drop_table('records')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_owner_id'))
        batch_op.drop_index('Index_category_global_name', postgresql_where=sa.text('owner_id IS NULL'))

    op.drop_table('categories')
    op.drop_table('users')
    # ### end Alembic commands ###
